# http://travis-ci.org/#!/dailymuse/torender

language: python
install:
    - pip install tox
    - npm install
script:
    - tox
env:
    - TRAVIS_NODE_VERSION=4 TOXENV=py27-tornado322
    - TRAVIS_NODE_VERSION=4 TOXENV=py27-tornado401
    - TRAVIS_NODE_VERSION=4 TOXENV=py34-tornado322
    - TRAVIS_NODE_VERSION=4 TOXENV=py34-tornado401
    - TRAVIS_NODE_VERSION=4 TOXENV=pypy-tornado322
    - TRAVIS_NODE_VERSION=4 TOXENV=pypy-tornado401
