# http://travis-ci.org/#!/dailymuse/torender

language: python
python:
    - "pypy"
env:
    - TRAVIS_NODE_VERSION="4" TOXENV=py27-tornado322
    - TRAVIS_NODE_VERSION="4" TOXENV=py27-tornado401
    - TRAVIS_NODE_VERSION="4" TOXENV=py34-tornado322
    - TRAVIS_NODE_VERSION="4" TOXENV=py34-tornado401
    - TRAVIS_NODE_VERSION="4" TOXENV=pypy-tornado322
    - TRAVIS_NODE_VERSION="4" TOXENV=pypy-tornado401
install:
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - pip install tox
    - npm install
script:
    - tox
